# Generated by Django 2.2.14 on 2021-10-30 12:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('production_desc', models.CharField(max_length=250)),
                ('unitprice', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_firmname', models.CharField(blank=True, max_length=250)),
                ('b_addr1', models.CharField(blank=True, max_length=250)),
                ('b_addr2', models.CharField(blank=True, max_length=250)),
                ('b_city', models.CharField(blank=True, max_length=250)),
                ('b_state', models.CharField(blank=True, max_length=250)),
                ('b_zip', models.CharField(blank=True, max_length=250)),
                ('b_country', models.CharField(blank=True, max_length=250)),
                ('s_firmname', models.CharField(blank=True, max_length=250)),
                ('s_addr1', models.CharField(blank=True, max_length=250)),
                ('s_addr2', models.CharField(blank=True, max_length=250)),
                ('s_city', models.CharField(blank=True, max_length=250)),
                ('s_state', models.CharField(blank=True, max_length=250)),
                ('s_zip', models.CharField(blank=True, max_length=250)),
                ('s_country', models.CharField(blank=True, max_length=250)),
                ('b_date', models.DateField()),
                ('b_buyer', models.CharField(blank=True, max_length=250)),
                ('b_purchase_order', models.CharField(blank=True, max_length=250)),
                ('b_tirms', models.CharField(blank=True, max_length=250)),
                ('contact1', models.CharField(blank=True, max_length=250)),
                ('contact2', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('payment_due_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.CharField(choices=[('A', 'Admin'), ('S', 'Sales'), ('C', 'Collection')], max_length=1)),
                ('contact', models.BigIntegerField()),
                ('sales_code', models.CharField(default='123454', max_length=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ou', models.CharField(max_length=250)),
                ('production_desc', models.CharField(max_length=250)),
                ('unitprice', models.CharField(max_length=250)),
                ('extend', models.CharField(max_length=250)),
                ('item', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='testapp.Product')),
                ('sale', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='testapp.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='Followupnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('sale', models.ForeignKey(default='b@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='testapp.Sales')),
            ],
        ),
    ]
